frequency: 20.0

# ROS params
local_goal_topic: /naviton/waypoint/wpManager/nowWpPose_local
local_map_topic: /naviton/planning/costmap/obstacle_costmap_generator/local_costmap
odom_topic: /naviton/mobile_base_controller/odom

cmd_vel_topic: /naviton/mobile_base_controller/cmd_vel

publish_trajectory: true
#trajectory_topic: 

# DWA params
target_velocity: 1.0

velocity_resolution: 20
yawrate_resolution: 10

predict_time: 1.0

error_cost_gain: 10.0
speed_cost_gain: 0.0
costmap_cost_gain: 0.05

obstacle_distance_threshould: 0.8 # [m]

# Robot params
min_velocity      : -0.1
max_velocity      : 1.0

max_yawrate       : 0.8

max_d_yawrate     : 5.0

max_acceleration  : 2.5