frequency: 20.0

# ROS params
local_goal_topic: /naviton/waypoint/wpManager/nowWpPose_local
local_map_topic: /naviton/planning/costmap/obstacle_costmap_generator/local_costmap
odom_topic: /naviton/mobile_base_controller/odom

cmd_vel_topic: /naviton/mobile_base_controller/cmd_vel

publish_trajectory: true
#trajectory_topic: 

# DWA params
target_velocity: 0.0

velocity_resolution: 16
yawrate_resolution: 16

predict_time: 3.0

error_cost_gain: 10.0
speed_cost_gain: 0.0
costmap_cost_gain: 0.025

obstacle_distance_threshould: 0.55 # [m]

# Robot params
min_linear_speed  : 0.15
min_angular_speed : 0.3
min_velocity      : -0.15
max_velocity      : 0.75

min_yawrate       : 0.3
max_yawrate       : 0.7

max_d_yawrate     : 4.0

max_acceleration  : 4.5