frequency               : 10  # [Hz]

topic_nowWp             : wpManager/nowWp
topic_nowWp_local       : wpManager/nowWp_local
topic_nowWpPose_local   : wpManager/nowWpPose_local
topic_waypoints         : wpLoader/waypoints
service_manager_set     : wpManager/set

lookupTimeout           : 0.2 # [s]

frame_id_robot          : base_link
frame_id_map            : map