frequency: 10  # [Hz]

topic_waypoints: wpLoader/waypoints

topic_absolute_position: "wpManager/absolute_position"

# 絶対座標（位置）
absolute_x: 10.0
absolute_y: 20.0
absolute_z: 0.0

# 絶対座標（回転：クォータニオン）
absolute_orientation_x: 0.0
absolute_orientation_y: 0.0
absolute_orientation_z: 0.0
absolute_orientation_w: 1.0  # 単位クォータニオン（回転なしの初期値）
