frequency : 10

goal_topic          : /waypoint_manager/wpManager/nowWpPose_local
costmap_topic       : /costmap_generator/local_costmap
path_topic          : local_path
a_star_goal_topic   : local_goal

robot_frame_id      : base_link

goal_distance       : 0.5 # [m]