frequency                 : 20              # [hz]

costmap_main_topic        : obstacle_costmap/inflated
costmap_main_magnification: 1.0
costmap_main_timeout      : 1.0             # [s]

costmap_sub_topic         : path_costmap
costmap_sub_magnification : 1.0
costmap_sub_timeout       : 1.0             # [s]

costmap_merged_topic      : local_costmap